#!/bin/bash
#PBS -l mem=20gb,nodes=1:ppn=8,walltime=12:00:00
#PBS -m abe
#PBS -M wyant008@umn.edu
#PBS -q lab

set -e
set -u
set -o pipefail

module load vcftools_ML
module load vcflib_ML/1.0.0
module load python

cd ~/shared/Projects/Barley_NAM_Parents/SNP_calling/Variants/Parts

echo "1. Gzip all the chromosome part vcfs" >&2

gzip GATK_chr*.vcf

echo "2. Concatenate the chromosome part vcfs" >&2

vcf-concat GATK_chr1H_part1.vcf.gz\
    GATK_chr1H_part2.vcf.gz\
    GATK_chr2H_part1.vcf.gz\
    GATK_chr2H_part2.vcf.gz\
    GATK_chr3H_part1.vcf.gz\
    GATK_chr3H_part2.vcf.gz\
    GATK_chr4H_part1.vcf.gz\
    GATK_chr4H_part2.vcf.gz\
    GATK_chr5H_part1.vcf.gz\
    GATK_chr5H_part2.vcf.gz\
    GATK_chr6H_part1.vcf.gz\
    GATK_chr6H_part2.vcf.gz\
    GATK_chr7H_part1.vcf.gz\
    GATK_chr7H_part2.vcf.gz\
    GATK_chrUn.vcf.gz > GATK_concat.vcf 

echo "3. Convert the physical positions" >&2

./Convert_Parts_To_Pseudomolecules.py GATK_concat.vcf > GATK_concat_Parts_To_Pseudomolecules.vcf

echo "4. Finished" >&2
